[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
dockerContext = "."

[deploy]
startCommand = "openresty"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10