upstream room  {
   server room-server.railway.internal:3333;
   keepalive 32;
}
upstream socket  {
   hash $remote_addr consistent;
   server room-server.railway.internal:3002;
   keepalive 32;
}
upstream socketRoom  {
   hash $remote_addr consistent;
   server room-server.railway.internal:3005;
   keepalive 32;
}
upstream document  {
   hash $remote_addr consistent;
   server room-server.railway.internal:3006;
   keepalive 32;
}
